// ignore_for_file: avoid_print

import 'dart:io';
import 'dart:isolate';
import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';

late final SendPort loggerSendPort;
bool _loggerStarted = false;

Future<void> initLoggerIsolate() async {
  if (_loggerStarted) return;

  final receivePort = ReceivePort();
  await Isolate.spawn(_loggerIsolate, receivePort.sendPort);
  loggerSendPort = await receivePort.first as SendPort;
  _loggerStarted = true;
}

void attachLogger(SendPort port) {
  loggerSendPort = port;
  _loggerStarted = true;
}

void logInfo(String message) {
  _sendLog(message, _LogType.info);
}

void logWarning(String message) {
  _sendLog(message, _LogType.warning);
}

void logError(String message, [StackTrace? stackTrace]) {
  if (stackTrace != null) {
    _sendLog('$message\n$stackTrace', _LogType.error);
  } else {
    _sendLog(message, _LogType.error);
  }
}

void _sendLog(String message, _LogType type) {
  if (!_loggerStarted) {
    print('Logger not initialized');
    return;
  }
  loggerSendPort.send(_LogMessage(message, type));
}

void _loggerIsolate(SendPort mainSendPort) {
  final receivePort = ReceivePort();
  mainSendPort.send(receivePort.sendPort);

  final time = DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());
  final file =
      File(
          kDebugMode
              ? 'build/falcon/logs/falcon_gui_$time.log'
              : '${Platform.environment['HOME'] ?? ''}/falcon/output/logs/falcon_gui_$time.log',
        )
        ..createSync(recursive: true)
        ..writeAsStringSync(_logFileHeader, mode: FileMode.append);

  print('\x1B[32mLog file created at: ${file.absolute.path}\x1B[0m');

  receivePort.listen((msg) {
    final timestamp = DateFormat(
      'yyyy-MM-dd HH:mm:ss.SSS',
    ).format(DateTime.now());

    String logMessage;

    if (msg is _LogMessage) {
      logMessage = msg.format;
      print(msg.formatWithColor);
    } else if (msg is List && msg.length == 2) {
      // This is an uncaught error from a sub-isolate
      final error = msg[0];
      final stackTrace = msg[1];

      logMessage =
          '[$timestamp] Uncaught isolate exception: $error\n$stackTrace';

      print('\x1B[31m$logMessage\x1B[0m');
    } else {
      logMessage = '[$timestamp] Unknown log message: $msg';
      print(logMessage);
    }

    file.writeAsStringSync('$logMessage\n', mode: FileMode.append);
  });
}

class _LogMessage {
  _LogMessage(this.message, this.type);
  final String message;
  final _LogType type;
  final String isolateName = Isolate.current.debugName ?? 'unknown';

  String get format {
    final timestamp = DateFormat(
      'yyyy-MM-dd HH:mm:ss.SSS',
    ).format(DateTime.now());

    return '[$timestamp] [$isolateName] [$type] $message';
  }

  String get formatWithColor => switch (type) {
    _LogType.info => _makeGreen(format),
    _LogType.warning => _makeYellow(format),
    _LogType.error => _makeRed(format),
  };

  String _makeRed(String input) {
    return '\x1B[31m$input\x1B[0m';
  }

  String _makeGreen(String input) {
    return '\x1B[32m$input\x1B[0m';
  }

  String _makeYellow(String input) {
    return '\x1B[33m$input\x1B[0m';
  }
}

enum _LogType {
  info,
  warning,
  error
  ;

  @override
  String toString() {
    switch (this) {
      case _LogType.info:
        return 'INFO';
      case _LogType.warning:
        return 'WARNING';
      case _LogType.error:
        return 'ERROR';
    }
  }
}

const _logFileHeader =
    '--- Falcon GUI Log Started ---\n'
    '--- Do not edit this file manually ---\n'
    '--- Use the Falcon GUI application to view logs ---\n'
    '-------------------------------------\n'
    '\n'
    'Timestamp Format: yyyy-MM-dd HH:mm:ss.SSS\n'
    '\n'
    'Log Levels:\n'
    'INFO: General informational messages\n'
    'WARNING: Potential issues that do not stop execution\n'
    'ERROR: Critical issues that may affect functionality\n'
    '\n'
    '-------------------------------------\n'
    '\n';
