graph:
  file: ""
  autostart: false
debug:
  enabled: false
network:
  port: 5555
logging:
  path: "./build/falcon/logs/"
server_side_storage:
  environment: "./build/falcon/output/"
  resources: "./build/falcon/resources/"
ui:
  theme_mode: "system"
  last_opened_graph: "/home/device/falcon/resources/graphs/current.yaml"
