graph:
  file: null
  autostart: null
debug:
  enabled: null
network:
  port: 5555
logging:
  path: "~/falcon/output/logs/"
server_side_storage:
  environment: "~/falcon/output/"
  resources: "~/falcon/resources/"
ui:
  theme_mode: "system"
  last_opened_graph: "/home/device/falcon/resources/graphs/my_graph.yaml"
