name: Build GUI

on:
  pull_request:
    branches: [develop]
    paths:
      - "falcon_gui/**"
      - ".github/workflows/build_gui.yml"

jobs:
  build-linux:
    name: Build GUI
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: falcon_gui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FVM and Flutter
        working-directory: . # To install FVM globally for the entire workflow
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          echo "/home/runner/fvm/bin" >> $GITHUB_PATH
          echo "/home/runner/fvm/versions/3.38.5/bin" >> $GITHUB_PATH
          export PATH="/home/runner/fvm/bin:$PATH"

          fvm install 3.38.5
          fvm global 3.38.5

      - name: Lint and format
        run: |
          flutter pub get
          dart format --set-exit-if-changed .
          flutter analyze --fatal-infos --fatal-warnings

      - name: Build project
        run: |
          # Ensure Linux build dependencies are present
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
          flutter build linux --release

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: falcon_gui
          path: falcon_gui/build/linux/x64/release/bundle/
          if-no-files-found: error