name: Build Falcon Core

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dummy step
      run: |
        echo "hello"
